### ISSUE TITLE
TODO - 2020 version

### ISSUE THREAD

**Issue by keunwoochoi** [keunwoochoi/kapre#80]
- [ ] Add inverse STFT
- [ ] Add a `composed` layer that concatenates magnitude and phase of input complex number (which would be STFT)

**Comment by keunwoochoi** [comment]
- [ ] mfcc?
- [ ] time-stretch? 
- [ ] frequency shift?

**Comment by keunwoochoi** [comment]
- [ ] fix test for phase

**Comment by keunwoochoi** [comment]
- [ ] energy
 - [ ] loudness 
 - [ ] HPSS

**Comment by keunwoochoi** [comment]
- [ ] tf.signal.frame

**Comment by keunwoochoi** [comment]
- [ ] frequency-aware conv layer? (@kkoutini any chance you'd be interested in making a PR?)

**Comment by keunwoochoi** [comment]
- [ ] `InstaneousFrequency(pad_end=True)`

**Comment by keunwoochoi** [comment]
change numpy requirements to 1.18.5 to be compatible with tensorflow.

**Comment by keunwoochoi** [comment]
typos ..  `retunrs`

**Comment by keunwoochoi** [comment]
- [ ] random gain (control the multiplication factor)
- [ ] random volume (control the output.. amplitude? energy?)

**Comment by keunwoochoi** [comment]
- [ ] more examples

- [ ] pre-structured models?
